# Database
spring.datasource.url=jdbc:postgresql://postgres-sql0-khushikohli333-0240.h.aivencloud.com:23535/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_JcRiqXiTkxliWNzAwD
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Server — MUST bind to 0.0.0.0 for Render
server.address=0.0.0.0
server.port=8080

# File upload
upload.dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.web.resources.static-locations=classpath:/static/,file:uploads/
